theme: jekyll-theme-minimal
repository: dimona-loves-animals/dimona-loves-animals.github.io.git
title: דימונה אוהבת חיות
description: מתנדבים למען בעלי החיים; למען דימונה.
logo: assets/brand/logo.png
google_analytics: [Your Google Analytics tracking ID]